server:
  port: 9090

spring:
  data:
    redis:
      host: localhost
      port: 63791

  datasource:
    url: jdbc:mysql://mysql:33061/treep
    username: root
    password: 2122
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        show_sql: true


jwt:
  issuer: jara
  subject: auth
  expires-time: 3600 # = 1h
  secret: treep-authentication-secret

logging:
  level:
    root: debug