server:
  port: 9090

spring:
  data:
    redis:
      host: localhost
      port: 63791

  datasource:
    url: jdbc:postgresql://localhost:54321/treep
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        show_sql: true


jwt:
  issuer: jara
  subject: auth
  expires-time: 3600 # = 1h
  secret: treep-authentication-secret

logging:
  level:
    root: debug