server:
  port: 9090

spring:
  data:
    redis:
      host: localhost
      port: 63791

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:54321/treep?serverTimezone=UTC
    username: postgres
    password: password

  jpa:
    show-sql: true
    properties:
      hibernate:
        check_nullability: true
        validator:
          apply_to_ddl: true
        jdbc.lob.non_contextual_creation: true
        default_schema: plan
        show_sql: true
    hibernate:
      ddl-auto: validate
    open-in-view: true


jwt:
  issuer: jara
  subject: auth
  expires-time: 3600 # = 1h
  secret: treep-authentication-secret

logging:
  level:
    root: debug