version: '3.1'
services:
  db:
    image: mysql:latest
    container_name: treep
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: treep
      MYSQL_ROOT_PASSWORD: 2122
    ports:
      - "3306:3306"

  redis:
    image: redis
    ports:
      - "6379:6379"