version: '3.1'
services:
  db:
    image: postgres:15.7-alpine3.20
    container_name: treep-postgres
    restart: always
    environment:
      POSTGRES_DB: treep
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "54321:5432"
    volumes:
      - ./.var/lib/postgresql/data:/var/lib/postgresql/data

  mock-server:
    image: nginx:latest
    container_name: auth-mock-server
    ports:
      - "9090:80"
    volumes:
      - ./mock-server/nginx.conf:/etc/nginx/nginx.conf
#
#  redis:
#    image: redis
#    ports:
#      - "63791:6379"