server:
  port: 8080

service:
  auth:
    url: http://localhost:9090/api/v1/users/info

spring:
  datasource:
    url: jdbc:mysql://mysql:3306/treep
    username: root
    password: 2122
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        show_sql: true
  docker:
    compose:
      start:
        log-level: debug
logging:
  level:
    root: debug
#        dialect: org.hibernate.dialect.MySQLDialect