server:
  port: 8080

service:
  auth:
    url: http://localhost:9090/api/v1/users/info

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:54321/treep
    username: postgres
    password: password

  data:
    redis:
      host: localhost
      port: 63791

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        check_nullability: true
        validator:
          apply_to_ddl: true

    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  docker:
    compose:
      start:
        log-level: debug
      file: classpath:docker-compose.yml

  jackson:
    serialization:
      write_dates_as_timestamps: false

logging:
  level:
    web: info
    org.springframework:
      boot: info
