### Post Plan
POST http://localhost:8080/v1/plans
Content-Type: application/json

{
  "title": "test plan",
  "startDate": "2024-05-31T09:30:00",
  "endDate": "2024-06-05T18:00:00",
  "budget": 500000
}

### Get Plans
GET http://localhost:8080/v1/plans

### Get Plan
GET http://localhost:8080/v1/plans/1