version: '3.1'
services:
  db:
    image: mysql:latest
    container_name: treep
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: treep
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: 2122
    ports:
      - "33061:3306"

  redis:
    image: redis
    ports:
      - "63791:6379"