server:
  port: 8080

service:
  auth:
    url: http://localhost:9090/api/v1/users/info

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:54321/treep?serverTimezone=UTC
    username: postgres
    password: password

  data:
    redis:
      host: localhost
      port: 63791
    mongodb:
      uri: mongodb://localhost:27017/treep

  jpa:
    show-sql: true
    properties:
      hibernate:
        check_nullability: true
        validator:
          apply_to_ddl: true
        jdbc.lob.non_contextual_creation: true
        default_schema: plan
        show_sql: true

    hibernate:
      ddl-auto: validate
    open-in-view: true

  docker:
    compose:
      start:
        log-level: debug

  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    enabled: false

logging:
  level:
    me.chnu: debug
    org.springframework:
      boot: info
    com.fasterxml.jackson: debug
