### 식사 일정 생성
POST http://localhost:8080/api/v1/plans/1/itineraries/dining
Content-Type: application/json

{
  "title": "아침 식사",
  "cost": 8000,
  "startAt": "2023-10-06T08:00:00",
  "endAt": "2023-10-06T09:00:00",
  "location": "서울 강남구",
  "restaurantName": "유명 순대국",
  "restaurantAddress": "서울시 강남구"
}

### 숙박 일정 생성
POST http://localhost:8080/api/v1/plans/1/itineraries/stay
Content-Type: application/json

{
  "title": "숙박",
  "cost": 50000,
  "startAt": "2023-10-06T22:00:00",
  "endAt": "2023-10-07T09:00:00",
  "location": "서울 강남구",
  "accommodationName": "편한 숙소",
  "accommodationAddress": "서울시 강남구"
}

### 일정 생성
POST http://localhost:8080//api/v1/plans/1/itineraries/any
Content-Type: application/json

{
"title": "숙박2",
"cost": 60000,
"startAt": "2023-10-06T22:00:00",
"endAt": "2023-10-07T09:00:00",
"location": "서울 강남구",
"accommodationName": "편한 숙소",
"accommodationAddress": "서울시 강남구"
}

### 일정 조회
GET http://localhost:8080/api/v1/plans/1/itineraries
