### 여행 계획 생성
POST http://localhost:8080/api/v1/plans
Content-Type: application/json

{
  "title": "논산 여행",
  "startDate": "2023-10-05T02:00:00",
  "endDate": "2023-10-26T09:00:00",
  "budget": 3000
}

### 여행 계획 조회
GET http://localhost:8080/api/v1/plans

### 여행 계획 상세 조회
GET http://localhost:8080/api/v1/plans/1

### 여행 계획 수정
PUT http://localhost:8080/api/v1/plans/1
Content-Type: application/json

{
  "title": "논산 여행",
  "startDate": "2023-10-05T02:00:00",
  "endDate": "2023-10-26T09:00:00",
  "budget": 6000
}

### 여행 계획 삭제
DELETE http://localhost:8080/api/v1/plans/1


