@base = http://localhost:8080
@plan-id = 10
@itinerary-id = 5

### Post Itinerary
POST {{base}}/v1/plans/{{plan-id}}/itineraries
Content-Type: application/json
Authorization: test

{
  "title":"밥먹기",
  "cost": 15000,
  "startAt":"2024-05-31T12:30:00Z",
  "endAt": "2024-05-31T11:30:00Z",
  "description":"점심",
  "parentId": 3
}

### Get Itineraries
GET {{base}}/v1/plans/{{plan-id}}}/itineraries
Authorization: test

### Get Itinerary
GET {{base}}/v1/plans/{{plan-id}}/itineraries/{{itinerary-id}}
Authorization: test

### Put Itinerary
PUT {{base}}/v1/plans/{{plan-id}}/itineraries/{{itinerary-id}}
Content-Type: application/json
Authorization: test

{
  "title":"밥먹기",
  "cost": 13000,
  "startAt":"2024-05-31T12:30:00Z",
  "endAt": "2024-05-31T11:30:00Z",
  "description":"점심",
  "parentId": 3
}