### Post Itinerary
POST http://localhost:8080/v1/plans/1/itineraries
Content-Type: application/json

{
  "title":"밥먹기",
  "cost": 15000,
  "startAt":"2024-05-31T12:30:00Z",
  "endAt": "2024-05-31T11:30:00Z",
  "description":"점심",
  "parentId": 3
}

### Get Itineraries
GET http://localhost:8080/v1/plans/1/itineraries

### Get Itinerary
GET http://localhost:8080/v1/plans/1/itineraries/1